### PR TITLE
 Translation

### PR DESCRIPTION
**Pull request by contreas99**
Translation into Italian

### CODE REVIEW

**Comment by rlnt** [comment]
Is this a work in progress?
The InsaneShops translation looks good but the UltraPunishments translation is incomplete.

Do you want to continue on that?

**Comment by contreas99** [comment]
Sure I'll do it tomorrow

**Comment by contreas99** [comment]
insaneshops: completed

ultrapunishment: completed

ultrapermissions: work in progress

**Comment by rlnt** [comment]
Please finish this pull request or it will be closed because of its stale status.

**Comment by rlnt** [comment]
This submission is closed because it's stale.

**Pull request closed without merging**
