### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by Azurz**

### CODE REVIEW

**Review by rlnt — COMMENTED** [review]
What about the phrases that you left out? Are those the same in French?

I am pretty sure phrases like "Maximum Active Connections" are not the same in French.

**Comment by Azurz** [comment]
There are some words yes and others just some forgetfulness I'll correct it tomorrow.

**Comment by Azurz** [comment]
Here's the rest it's the same in English as in French

**Review by rlnt — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
